LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.all;


ENTITY C_U IS
  PORT (
    CLK : IN  STD_LOGIC;                    
    ADD_DIGIT : IN  STD_LOGIC; 
    VALIDATE_PIN: IN STD_LOGIC;
    RESET: IN STD_LOGIC;
    FREE_OCCUPIED_LED : INOUT STD_LOGIC;
    ENTER_CHARACTERS_LED: INOUT STD_LOGIC; 
    COUNTER_RESET:INOUT STD_LOGIC
    );
END C_U;

ARCHITECTURE TypeArchitecture OF C_U IS

COMPONENT DEBOUNCER1 IS
    Port ( CLK100MHZ : in STD_LOGIC;
           BUTTON : in STD_LOGIC;
           BUTTON_DS : out STD_LOGIC);
END COMPONENT;

TYPE STATE IS (IDLE, ADD_DIGIT1_UNLOCKED,STORE_DIGIT1_UNLOCKED,ADD_DIGIT2_UNLOCKED,STORE_DIGIT2_UNLOCKED,ADD_DIGIT3_UNLOCKED,STORE_DIGIT3_UNLOCKED,LOCKED_STATE,ADD_DIGIT1_LOCKED,STORE_DIGIT1_LOCKED,ADD_DIGIT2_LOCKED,STORE_DIGIT2_LOCKED,ADD_DIGIT3_LOCKED,STORE_DIGIT3_LOCKED, COMPARE);
SIGNAL CURRENT_STATE,NEXT_STATE : STATE;
SIGNAL DIGIT:STD_LOGIC;

BEGIN 
DEBOUNCER: DEBOUNCER1 PORT MAP(CLK100MHZ => CLK, BUTTON => ADD_DIGIT,BUTTON_DS => DIGIT);	
UPDATE_STATE: PROCESS (RESET,CLK)
BEGIN 
	IF RESET = '1' THEN 
		CURRENT_STATE <= IDLE;
	ELSIF CLK'EVENT AND CLK = '1' THEN
		CURRENT_STATE <= NEXT_STATE;
	END IF;
END PROCESS UPDATE_STATE;	
TRANSITIONS: PROCESS(CURRENT_STATE,DIGIT, VALIDATE_PIN)
BEGIN
	COUNTER_RESET<='1'; FREE_OCCUPIED_LED<='0'; ENTER_CHARACTERS_LED<='0';
	CASE CURRENT_STATE IS 
	   WHEN IDLE =>
	       COUNTER_RESET<='1';
	       IF DIGIT = '1' THEN
	           NEXT_STATE <= ADD_DIGIT1_UNLOCKED;
	       ELSE
	           NEXT_STATE <= IDLE;
	       END IF;
	   WHEN ADD_DIGIT1_UNLOCKED =>
	       ENTER_CHARACTERS_LED <= '1'; COUNTER_RESET<='0';
	       IF DIGIT = '1' THEN
	           NEXT_STATE <= STORE_DIGIT1_UNLOCKED;
	       ELSE 
	           NEXT_STATE <= ADD_DIGIT1_UNLOCKED;
	       END IF;
	   WHEN STORE_DIGIT1_UNLOCKED =>
	       ENTER_CHARACTERS_LED <= '1'; COUNTER_RESET<='1';
	       NEXT_STATE <= ADD_DIGIT2_UNLOCKED;
	   WHEN ADD_DIGIT2_UNLOCKED =>
           ENTER_CHARACTERS_LED <= '1'; COUNTER_RESET<='0';
           IF DIGIT = '1' THEN
               NEXT_STATE <= STORE_DIGIT2_UNLOCKED;
           ELSE 
               NEXT_STATE <= ADD_DIGIT2_UNLOCKED;
           END IF;      
        WHEN STORE_DIGIT2_UNLOCKED =>
           ENTER_CHARACTERS_LED <= '1'; COUNTER_RESET<='1';
           NEXT_STATE <= ADD_DIGIT3_UNLOCKED;
        WHEN ADD_DIGIT3_UNLOCKED =>
           ENTER_CHARACTERS_LED <= '1'; COUNTER_RESET<='0'; 
           IF DIGIT = '1' THEN
              NEXT_STATE <= STORE_DIGIT3_UNLOCKED;
           ELSE 
              NEXT_STATE <= ADD_DIGIT3_UNLOCKED;
           END IF;  
        WHEN STORE_DIGIT3_UNLOCKED =>
           ENTER_CHARACTERS_LED <= '1'; COUNTER_RESET<='1'; 
           NEXT_STATE <= LOCKED_STATE;    
        WHEN LOCKED_STATE =>
           FREE_OCCUPIED_LED <= '1';
           IF DIGIT = '1' THEN
                NEXT_STATE <= ADD_DIGIT1_LOCKED;
           ELSE
                NEXT_STATE <= LOCKED_STATE;
           END IF;
        WHEN ADD_DIGIT1_LOCKED =>
            FREE_OCCUPIED_LED <= '1'; ENTER_CHARACTERS_LED <= '1'; COUNTER_RESET<='0';
            IF DIGIT = '1' THEN
                NEXT_STATE <= STORE_DIGIT1_LOCKED;
            ELSE 
                NEXT_STATE <= ADD_DIGIT1_LOCKED;
            END IF;                 
        WHEN STORE_DIGIT1_LOCKED =>
            FREE_OCCUPIED_LED <= '1'; ENTER_CHARACTERS_LED <= '1'; COUNTER_RESET<='1';
            NEXT_STATE <= ADD_DIGIT2_LOCKED;        
        WHEN ADD_DIGIT2_LOCKED =>
            FREE_OCCUPIED_LED <= '1'; ENTER_CHARACTERS_LED <= '1'; COUNTER_RESET<='0';
            IF DIGIT = '1' THEN
                NEXT_STATE <= STORE_DIGIT2_LOCKED; 
            ELSE 
                NEXT_STATE <= ADD_DIGIT2_LOCKED;
            END IF;           
        WHEN STORE_DIGIT2_LOCKED =>
            FREE_OCCUPIED_LED <= '1'; ENTER_CHARACTERS_LED <= '1'; COUNTER_RESET<='1';
            NEXT_STATE <= ADD_DIGIT3_LOCKED;       
        WHEN ADD_DIGIT3_LOCKED =>
            FREE_OCCUPIED_LED <= '1'; ENTER_CHARACTERS_LED <= '1'; COUNTER_RESET<='0';
            IF DIGIT = '1' THEN
                NEXT_STATE <= STORE_DIGIT3_LOCKED;
            ELSE 
                NEXT_STATE <= ADD_DIGIT3_LOCKED;
            END IF;  
        WHEN STORE_DIGIT3_LOCKED =>
            FREE_OCCUPIED_LED <= '1'; ENTER_CHARACTERS_LED <= '1'; COUNTER_RESET<='1';
            NEXT_STATE <= COMPARE;                  
        WHEN COMPARE =>
            FREE_OCCUPIED_LED <= '1'; ENTER_CHARACTERS_LED <= '1'; COUNTER_RESET<='1';
            IF VALIDATE_PIN = '1' THEN 
                NEXT_STATE <= IDLE;
            ELSE
                NEXT_STATE <= LOCKED_STATE;
            END IF;
    END CASE;
END PROCESS TRANSITIONS;
END TypeArchitecture;
