library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.STD_LOGIC_UNSIGNED.ALL;


entity COUNTER is
    Port (
    Q_OUT:inOUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    RESET:IN STD_LOGIC;
    CNT_UP:IN STD_LOGIC;
    CNT_DN:IN STD_LOGIC;
    CLK:IN STD_LOGIC;
    COUNTER_RESET: IN STD_LOGIC
    );
end COUNTER;

architecture Behavioral of COUNTER is

COMPONENT DEBOUNCER2 is
    Port ( CLK100MHZ : in STD_LOGIC;
           BUTTON : in STD_LOGIC;
           BUTTON_DS : out STD_LOGIC
           );
END COMPONENT;

COMPONENT FREQUENCY_DIVIDER is
    Port ( CLK100 : in STD_LOGIC;
           CLK_OUT : out STD_LOGIC);
END COMPONENT;

COMPONENT DEBOUNCER1 is
    Port ( CLK100MHZ : in STD_LOGIC;
           BUTTON : in STD_LOGIC;
           BUTTON_DS : out STD_LOGIC
           );
END COMPONENT;

SIGNAL CNT_DN_DB, CNT_UP_DB:STD_LOGIC;
SIGNAL OUTPUT: STD_LOGIC_VECTOR(3 DOWNTO 0);
SIGNAL CLK_OUT:STD_LOGIC;

BEGIN

COUNT_UP:DEBOUNCER2 PORT MAP(CLK100MHZ=>CLK, BUTTON=>CNT_UP, BUTTON_DS=>CNT_UP_DB);
COUNT_DN:DEBOUNCER2 PORT MAP(CLK100MHZ=>CLK, BUTTON=>CNT_DN, BUTTON_DS=>CNT_DN_DB);
FREQ_DIV:FREQUENCY_DIVIDER PORT MAP(CLK100=>CLK, CLK_OUT=>CLK_OUT);
PROCESS(CLK_OUT)
BEGIN
    IF RISING_EDGE(CLK_OUT) THEN
        IF RESET = '1' OR COUNTER_RESET = '1' THEN
            OUTPUT <= "0000";
        ELSE
            IF CNT_UP_DB = '1' AND CNT_DN_DB = '0' THEN 
                OUTPUT <= OUTPUT + 1;
            ELSIF CNT_DN_DB = '1' AND CNT_UP_DB = '0' THEN
                OUTPUT <= OUTPUT - 1;
            END IF;
        END IF;
    END IF;
END PROCESS;
Q_OUT <= OUTPUT;
end Behavioral;