library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_UNSIGNED.ALL;


entity SSD_DISPLAY is
  Port (CLK100:IN STD_LOGIC;
        NUM1, NUM2, NUM3:IN STD_LOGIC_VECTOR(3 DOWNTO 0);
        CATODE:OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
        ANODE: OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
        ENABLE_NUM1, ENABLE_NUM2, ENABLE_NUM3:STD_LOGIC
   );
end SSD_DISPLAY;

architecture Behavioral of SSD_DISPLAY is

COMPONENT HEX_DECODER IS
  PORT (
	NUM: IN STD_LOGIC_VECTOR (3 DOWNTO 0);
	NUM_SSD: OUT STD_LOGIC_VECTOR (7 DOWNTO 0)
    );
END COMPONENT;    


SIGNAL SEL:STD_LOGIC_VECTOR(1 DOWNTO 0);
SIGNAL COUNT:STD_LOGIC_VECTOR(15 DOWNTO 0) :=(OTHERS=>'0');
SIGNAL NUM:STD_LOGIC_VECTOR(3 DOWNTO 0);
SIGNAL NUM_SSD:STD_LOGIC_VECTOR( 7 DOWNTO 0);

begin

DCD: HEX_DECODER port MAP(NUM=>NUM, NUM_SSD=>NUM_SSD);

 CNT:PROCESS(CLK100)

BEGIN

IF(RISING_EDGE(CLK100)) THEN

COUNT<=COUNT+1;
    IF(COUNT=x"FFFF") THEN   
    COUNT<=(OTHERS=>'0');

    END IF;
END IF;
END PROCESS;
SEL<=COUNT(15 DOWNTO 14);


 ANOD:PROCESS(SEL)
 
 BEGIN 
 CASE(SEL) IS
 WHEN "00" => ANODE<=(0 => '0', OTHERS => '1');
 WHEN "01" => ANODE<=(1 => '0', OTHERS => '1');
 WHEN "10" => ANODE<=(2 => '0', OTHERS => '1');
 WHEN "11" => ANODE<=(3 => '0', OTHERS => '1');
 END CASE;
END PROCESS;


 CATOD: PROCESS(SEL)
 begin
 CASE(SEL) IS
  WHEN "00" =>
   IF(ENABLE_NUM1='1') THEN 
   NUM<=NUM1;
   CATODE<=NUM_SSD;
   ELSE CATODE<=X"FF";
   END IF;
  WHEN "01" =>
  IF(ENABLE_NUM2='1') THEN 
     NUM<=NUM2;
     CATODE<=NUM_SSD;
     ELSE CATODE<=X"FF";
     END IF; 
  WHEN "10" => 
  IF(ENABLE_NUM3='1') THEN 
     NUM<=NUM3;
     CATODE<=NUM_SSD;
     ELSE CATODE<=X"FF";
     END IF;
  WHEN "11" => CATODE<=X"FF";
  END CASE;

END PROCESS;


end Behavioral;


